// Copyright 2020-present Etherna SA
// This file is part of MongODM.
//
// MongODM is free software: you can redistribute it and/or modify it under the terms of the
// GNU Lesser General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// MongODM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along with MongODM.
// If not, see <https://www.gnu.org/licenses/>.

using Etherna.MongoDB.Bson;
using Etherna.MongoDB.Driver;
using Etherna.MongODM.Core.ExecContext;
using Etherna.MongODM.Core.ExecContext.AsyncLocal;
using Etherna.MongODM.Core.Extensions;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Etherna.MongODM.Core.Utility
{
    /* The lock is a single lease document per db context, keyed by the db context identifier.
     * The claim is one upsert: with a live lease the expiration filter matches nothing and the
     * insert collides on the unique id index, reporting a duplicate key error, while an expired
     * lease matches and is taken over. Concurrent claimers serialize on the id index, so exactly
     * one wins, from whatever process. A document without a date expiration (hand edited, or
     * partially written) counts as expired, so the lock always self heals with the next claim.
     *
     * The lease duration chosen by the claim travels in the lease document: claimer and renewer
     * are frequently different processes (a dashboard web process claims the lock starting a
     * migration, and the background worker executing it resumes and renews the claim), so the
     * renewals read the chosen duration from the document instead of a value held in memory by
     * whoever resumes.
     *
     * A resumed claim stamps a fresh lease id, and renewals and releases are guarded by owner
     * and lease id together: the owner alone can't fence two executions of the same operation
     * (a background task runner delivering it twice), where the loser would otherwise release
     * the lease of the winner. A second resume invalidates the first, which loses its lease.
     * Expirations compare instants generated by different client clocks: the lease duration is
     * generous on purpose, keeping the ordinary clock skew between application instances
     * irrelevant.
     *
     * The lock collection is deliberately accessed raw, out of the engine access limitations:
     * the lock is the coordination infrastructure of the exclusive works, so it must stay
     * writable while an exclusive access denies the collections, and real also inside a
     * simulated flow. */
    public sealed class DbContextLock : IDbContextLock
    {
        // Consts.
        /// <summary>
        /// Duration of a lease claimed without an explicit one.
        /// </summary>
        public static readonly TimeSpan DefaultLeaseDuration = TimeSpan.FromMinutes(10);

        private const string ExpirationTimeElementName = "ExpirationTime";
        private const string LeaseDurationTicksElementName = "LeaseDurationTicks";
        private const string LeaseIdElementName = "LeaseId";
        private const string LeaseKey = "DbContextLockLease";

        /// <summary>
        /// Shortest claimable lease duration: the renewal interval is a fraction of the lease
        /// duration, and a lease renewed at a null interval would spin its renewals.
        /// </summary>
        public static readonly TimeSpan MinLeaseDuration = TimeSpan.FromTicks(RenewalsPerLease);

        private const string OwnerElementName = "Owner";
        //renewals attempted inside a lease duration: transient failures must find further retries
        private const int RenewalsPerLease = 5;

        // Fields.
        private readonly IExecutionContext executionContext;
        private readonly IMongoCollection<BsonDocument> lockCollection;
        private readonly string lockId;
        private readonly ILogger logger;

        // Constructor.
        /// <summary>
        /// Build the lock of a db context over its raw lease collection.
        /// </summary>
        /// <param name="lockCollection">The collection persisting the lease documents</param>
        /// <param name="lockId">The lock identifier, one per db context</param>
        /// <param name="executionContext">The execution context registering the ambient leases</param>
        /// <param name="logger">The logger</param>
        public DbContextLock(
            IMongoCollection<BsonDocument> lockCollection,
            string lockId,
            IExecutionContext executionContext,
            ILogger logger)
        {
            ArgumentNullException.ThrowIfNull(lockCollection);
            ArgumentNullException.ThrowIfNull(lockId);
            ArgumentNullException.ThrowIfNull(executionContext);
            ArgumentNullException.ThrowIfNull(logger);

            this.lockCollection = lockCollection;
            this.lockId = lockId;
            this.executionContext = executionContext;
            this.logger = logger;
        }

        // Methods.
        public async Task<bool> IsLockedAsync() =>
            await lockCollection.CountDocumentsAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.Gt(ExpirationTimeElementName, DateTime.UtcNow))).ConfigureAwait(false) > 0;

        public async Task<bool> TryClaimAsync(string ownerId, TimeSpan? leaseDuration = null)
        {
            ArgumentNullException.ThrowIfNull(ownerId);

            var claimedLeaseDuration = leaseDuration ?? DefaultLeaseDuration;
            ArgumentOutOfRangeException.ThrowIfLessThan(claimedLeaseDuration, MinLeaseDuration, nameof(leaseDuration));

            var now = DateTime.UtcNow;
            try
            {
                /* The expiration comparison is type bracketed on the server: a document
                 * without a date expiration matches no comparison, so it takes an explicit
                 * type predicate to be claimable instead of deadlocking the lock forever. */
                await lockCollection.UpdateOneAsync(
                    Builders<BsonDocument>.Filter.And(
                        Builders<BsonDocument>.Filter.Eq("_id", lockId),
                        Builders<BsonDocument>.Filter.Or(
                            Builders<BsonDocument>.Filter.Lt(ExpirationTimeElementName, now),
                            Builders<BsonDocument>.Filter.Not(
                                Builders<BsonDocument>.Filter.Type(ExpirationTimeElementName, BsonType.DateTime)))),
                    Builders<BsonDocument>.Update
                        .Set(OwnerElementName, ownerId)
                        .Set(ExpirationTimeElementName, now + claimedLeaseDuration)
                        .Set(LeaseDurationTicksElementName, claimedLeaseDuration.Ticks)
                        .Unset(LeaseIdElementName),
                    new UpdateOptions { IsUpsert = true }).ConfigureAwait(false);

                return true;
            }
            catch (MongoWriteException e) when (e.WriteError is { Category: ServerErrorCategory.DuplicateKey })
            {
                //another owner holds a live lease
                return false;
            }
        }

        public IDbContextLockLease? TryGetAmbientLease()
        {
            var leases = executionContext.TryGetItemsList<DbContextLockLease>(LeaseKey);
            if (leases is null)
                return null;

            /* Get the innermost lease of this same lock with a stack system, like the other
             * ambient handlers resolve their own: a flow can hold the leases of different db
             * context locks, and a lease of another lock doesn't own this one. */
            lock (((ICollection)leases).SyncRoot)
                return leases
                    .Where(lease => lease.LockId == lockId)
                    .Reverse()
                    .FirstOrDefault();
        }

        public Task TryReleaseAsync(string ownerId)
        {
            ArgumentNullException.ThrowIfNull(ownerId);

            return ReleaseLockAsync(Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId));
        }

        public async Task<IDbContextLockLease?> TryResumeClaimAsync(string ownerId)
        {
            ArgumentNullException.ThrowIfNull(ownerId);

            var leaseId = Guid.NewGuid().ToString();
            var leaseDuration = await TryStampLeaseAsync(ownerId, leaseId).ConfigureAwait(false);
            if (leaseDuration is null)
                return null;

            try
            {
                return new DbContextLockLease(this, ownerId, leaseId, leaseDuration.Value);
            }
            catch
            {
                //the stamp already extended the lease: without an owning lease nobody would release it
                await ReleaseLockAsync(
                    Builders<BsonDocument>.Filter.And(
                        Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId),
                        Builders<BsonDocument>.Filter.Eq(LeaseIdElementName, leaseId))).ConfigureAwait(false);
                throw;
            }
        }

        // Helpers.
        private Task<DeleteResult> ReleaseLockAsync(FilterDefinition<BsonDocument> ownershipFilter) =>
            lockCollection.DeleteOneAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    ownershipFilter));

        private async Task<bool> TryRenewLeaseAsync(string ownerId, string leaseId, TimeSpan leaseDuration)
        {
            var result = await lockCollection.UpdateOneAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId),
                    Builders<BsonDocument>.Filter.Eq(LeaseIdElementName, leaseId)),
                Builders<BsonDocument>.Update
                    .Set(ExpirationTimeElementName, DateTime.UtcNow + leaseDuration)).ConfigureAwait(false);

            return result.MatchedCount > 0;
        }

        /// <summary>
        /// Stamp a fresh lease id on the lock document of an owner, reading back the lease
        /// duration its claim chose, and extend the expiration by it.
        /// </summary>
        /// <param name="ownerId">The owner identifier used by the claim</param>
        /// <param name="leaseId">The lease identifier of this resume</param>
        /// <returns>The lease duration the renewals must use, or null when the owner doesn't
        /// hold the lock anymore</returns>
        private async Task<TimeSpan?> TryStampLeaseAsync(string ownerId, string leaseId)
        {
            var leaseDocument = await lockCollection.FindOneAndUpdateAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId)),
                Builders<BsonDocument>.Update
                    .Set(LeaseIdElementName, leaseId),
                new FindOneAndUpdateOptions<BsonDocument, BsonDocument>
                {
                    ReturnDocument = ReturnDocument.After
                }).ConfigureAwait(false);

            if (leaseDocument is null)
                return null;

            /* A lease document carrying no duration, or one too short to derive a renewal
             * interval from, renews on the default: the alternative would be a claim nobody
             * can resume, holding the lock until its expiration. */
            var leaseDuration =
                leaseDocument.TryGetValue(LeaseDurationTicksElementName, out var leaseDurationTicks) &&
                leaseDurationTicks.IsNumeric &&
                leaseDurationTicks.ToInt64() >= MinLeaseDuration.Ticks
                    ? TimeSpan.FromTicks(leaseDurationTicks.ToInt64())
                    : DefaultLeaseDuration;

            //the stamp doesn't extend the expiration by itself: the first renewal of the lease does
            return await TryRenewLeaseAsync(ownerId, leaseId, leaseDuration).ConfigureAwait(false)
                ? leaseDuration
                : null;
        }

        // Nested types.
        private sealed class DbContextLockLease : IDbContextLockLease
        {
            // Fields.
            private readonly IAsyncLocalContextHandler? asyncLocalContextHandler;
            private readonly DbContextLock dbContextLock;
            private int disposals;
            private DateTime lastRenewalTime;
            private readonly TimeSpan leaseDuration;
            private readonly string leaseId;
            private readonly CancellationTokenSource leaseLostTokenSource = new();
            private readonly ICollection<DbContextLockLease> leases;
            private readonly TimeSpan renewalInterval;
            private readonly CancellationTokenSource renewalStopTokenSource = new();
            private readonly Task renewalTask;

            // Constructor and dispose.
            public DbContextLockLease(
                DbContextLock dbContextLock,
                string ownerId,
                string leaseId,
                TimeSpan leaseDuration)
            {
                this.dbContextLock = dbContextLock;
                this.leaseDuration = leaseDuration;
                this.leaseId = leaseId;
                //the duration chosen by the claim drives the renewals of every owner resuming it
                renewalInterval = leaseDuration / RenewalsPerLease;
                OwnerId = ownerId;
                lastRenewalTime = DateTime.UtcNow; //the resume already renewed the lease

                var executionContext = dbContextLock.executionContext;

                if (executionContext.Items is null) //if an execution context doesn't exist, create it
                    asyncLocalContextHandler = AsyncLocalContext.Instance.InitAsyncLocalContext();

                leases = executionContext.GetOrAddItemsList<DbContextLockLease>(LeaseKey);

                lock (((ICollection)leases).SyncRoot)
                    leases.Add(this);

                renewalTask = KeepLeaseRenewedAsync();
            }

            public async ValueTask DisposeAsync()
            {
                if (Interlocked.Exchange(ref disposals, 1) != 0)
                    return;

                // Stop the background renewal.
                /* A faulted renewal task must neither skip the release below, nor replace the
                 * exception of the work run under the lease: report it and proceed. */
                try
                {
                    await renewalStopTokenSource.CancelAsync().ConfigureAwait(false);
                    await renewalTask.ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    dbContextLock.logger.DbContextLockLeaseRenewalFailed(dbContextLock.lockId, OwnerId, e);
                }

                lock (((ICollection)leases).SyncRoot)
                    leases.Remove(this);

                // Release the lock, permitting new claims without waiting the lease expiration.
                /* The delete is guarded by owner and lease id: releasing a lease already taken
                 * over, or invalidated by another resume of the same owner, is a no-op. A
                 * release failing (e.g. an unreachable server) leaves the lease expiring on
                 * its own: log it, without masking any exception of the work run under it. */
                try
                {
                    await dbContextLock.ReleaseLockAsync(
                        Builders<BsonDocument>.Filter.And(
                            Builders<BsonDocument>.Filter.Eq(OwnerElementName, OwnerId),
                            Builders<BsonDocument>.Filter.Eq(LeaseIdElementName, leaseId))).ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    dbContextLock.logger.DbContextLockReleaseFailed(dbContextLock.lockId, OwnerId, e);
                }

                leaseLostTokenSource.Dispose();
                renewalStopTokenSource.Dispose();
                asyncLocalContextHandler?.Dispose();
            }

            // Properties.
            public CancellationToken LeaseLostToken => leaseLostTokenSource.Token;
            //identifies the lock owning this lease, resolving the ambient leases of a flow
            public string LockId => dbContextLock.lockId;
            public string OwnerId { get; }

            // Helpers.
            private async Task KeepLeaseRenewedAsync()
            {
                try
                {
                    while (true)
                    {
                        await Task.Delay(renewalInterval, renewalStopTokenSource.Token).ConfigureAwait(false);
                        try
                        {
                            if (await dbContextLock.TryRenewLeaseAsync(OwnerId, leaseId, leaseDuration).ConfigureAwait(false))
                            {
                                lastRenewalTime = DateTime.UtcNow;
                                continue;
                            }

                            //the lease has been taken over, or invalidated by another resume
                            dbContextLock.logger.DbContextLockLeaseLost(dbContextLock.lockId, OwnerId);
                        }
                        catch (Exception e) when (e is not OperationCanceledException)
                        {
                            /* A transient failure: keep renewing, the lease survives until its
                             * expiration. Renewals failing for the whole lease duration end it:
                             * the lease can't be assumed alive anymore, and another claimer can
                             * already have taken the lock over. */
                            dbContextLock.logger.DbContextLockLeaseRenewalFailed(dbContextLock.lockId, OwnerId, e);

                            if (DateTime.UtcNow - lastRenewalTime < leaseDuration)
                                continue;

                            dbContextLock.logger.DbContextLockLeaseLost(dbContextLock.lockId, OwnerId);
                        }

                        await leaseLostTokenSource.CancelAsync().ConfigureAwait(false);
                        return;
                    }
                }
                catch (OperationCanceledException)
                {
                    //normal renewal stop at disposal
                }
            }
        }
    }
}
