<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Etherna.Scrinium.AspNetCoreSample</RootNamespace>

    <Authors>Etherna SA</Authors>
    <IsPackable>false</IsPackable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Scrinium.Core.Generators\Scrinium.Core.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\Scrinium.AspNetCore.UI\Scrinium.AspNetCore.UI.csproj" />
    <ProjectReference Include="..\..\src\Scrinium\Scrinium.csproj" />
  </ItemGroup>

</Project>
