// Copyright 2020-present Etherna SA
// This file is part of MongODM.
//
// MongODM is free software: you can redistribute it and/or modify it under the terms of the
// GNU Lesser General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// MongODM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along with MongODM.
// If not, see <https://www.gnu.org/licenses/>.

using Etherna.MongoDB.Bson;
using Etherna.MongoDB.Driver;
using Etherna.Scrinium.Core.ExecContext;
using Etherna.Scrinium.Core.ExecContext.AsyncLocal;
using Etherna.Scrinium.Core.Extensions;
using Microsoft.Extensions.Logging;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Etherna.Scrinium.Core.Utility
{
    /* The lock is a single lease document per resource, keyed by the lock identifier: the
     * db context engine binds one lock to its own identifier, coordinating its exclusive
     * works, and applications bind their own locks to the namespaced resource ids they
     * choose.
     *
     * The exclusive claim is one upsert: with a live lease the expiration filter matches
     * nothing and the insert collides on the unique id index, reporting a duplicate key
     * error, while an expired lease matches and is taken over. Concurrent claimers serialize
     * on the id index, so exactly one wins, from whatever process. A document without a date
     * expiration (hand edited, or partially written) counts as expired, so the lock always
     * self heals with the next claim.
     *
     * The shared mode admits any number of holders on one resource, each with its own lease
     * entry in the shared leases array: a shared acquisition is denied only by a live
     * exclusive lease, and an exclusive claim by any live lease. The top level expiration
     * always tracks the furthest lease, kept there by the shared acquisitions and renewals,
     * so claims, state reads and the TTL collection read the same element whatever the mode,
     * and a dead holder expires alone, instead of leaking a holders count nobody decrements.
     *
     * The lease duration chosen by a claim travels in the lease document: claimer and
     * renewer are frequently different processes (a dashboard web process claims the lock
     * starting a migration, and the background worker executing it resumes and renews the
     * claim), so the renewals read the chosen duration from the document instead of a value
     * held in memory by whoever resumes.
     *
     * A resumed claim stamps a fresh lease id, and renewals and releases are guarded by owner
     * and lease id together: the owner alone can't fence two executions of the same operation
     * (a background task runner delivering it twice), where the loser would otherwise release
     * the lease of the winner. A second resume invalidates the first, which loses its lease.
     * The shared leases are fenced the same way, each by its own lease id. Expirations
     * compare instants generated by different client clocks: the lease duration is generous
     * on purpose, keeping the ordinary clock skew between application instances irrelevant.
     *
     * The lock collection is deliberately accessed raw, out of the engine access limitations:
     * the locks are the coordination infrastructure of the works those limitations serve, so
     * they must stay claimable and renewable while an exclusive access denies the
     * collections, and real also inside a simulated flow. An abandoned lock document stops
     * locking at its expiration, and the TTL index of the collection garbage collects it. */
    public sealed class ResourceLock : IResourceLock
    {
        // Consts.
        /// <summary>
        /// How long an expired lock document is retained before the TTL index created by
        /// <see cref="CreateAbandonedDocumentsTtlIndexAsync"/> collects it. An expired
        /// document stops locking anything at its expiration: the retention only keeps it
        /// inspectable before the garbage collection.
        /// </summary>
        public static readonly TimeSpan AbandonedDocumentRetention = TimeSpan.FromDays(1);

        /// <summary>
        /// Name of the TTL index created by <see cref="CreateAbandonedDocumentsTtlIndexAsync"/>.
        /// </summary>
        public const string AbandonedDocumentsTtlIndexName = "AbandonedDocumentsTtl";

        /// <summary>
        /// Duration of a lease claimed without an explicit one.
        /// </summary>
        public static readonly TimeSpan DefaultLeaseDuration = TimeSpan.FromMinutes(10);

        private const string ExpirationTimeElementName = "ExpirationTime";
        private const string LeaseDurationTicksElementName = "LeaseDurationTicks";
        private const string LeaseIdElementName = "LeaseId";
        private const string LeaseKey = "ResourceLockLease";

        /// <summary>
        /// Shortest claimable lease duration: the renewal interval is a fraction of the lease
        /// duration, and a lease renewed at a null interval would spin its renewals.
        /// </summary>
        public static readonly TimeSpan MinLeaseDuration = TimeSpan.FromTicks(RenewalsPerLease);

        private const string OwnerElementName = "Owner";
        //renewals attempted inside a lease duration: transient failures must find further retries
        private const int RenewalsPerLease = 5;
        //upserts attempted by a shared acquisition against the insert collisions of concurrent claims
        private const int SharedAcquireMaxAttempts = 3;
        private const string SharedLeasesElementName = "SharedLeases";

        // Fields.
        private readonly IExecutionContext executionContext;
        private readonly IMongoCollection<BsonDocument> lockCollection;
        private readonly string lockId;
        private readonly ILogger logger;
        private readonly Func<Task>? prepareCollectionAsync;

        // Constructor.
        /// <summary>
        /// Build a lock over its raw lease collection.
        /// </summary>
        /// <param name="lockCollection">The collection persisting the lease documents</param>
        /// <param name="lockId">The lock identifier: the id of its lease document</param>
        /// <param name="executionContext">The execution context registering the ambient leases</param>
        /// <param name="logger">The logger</param>
        /// <param name="prepareCollectionAsync">Preparation awaited before every claim or
        /// acquisition (e.g. ensuring the TTL index of the collection); the caller shares one
        /// preparation across the locks of a collection</param>
        public ResourceLock(
            IMongoCollection<BsonDocument> lockCollection,
            string lockId,
            IExecutionContext executionContext,
            ILogger logger,
            Func<Task>? prepareCollectionAsync = null)
        {
            ArgumentNullException.ThrowIfNull(lockCollection);
            ArgumentNullException.ThrowIfNull(lockId);
            ArgumentNullException.ThrowIfNull(executionContext);
            ArgumentNullException.ThrowIfNull(logger);

            this.lockCollection = lockCollection;
            this.lockId = lockId;
            this.executionContext = executionContext;
            this.logger = logger;
            this.prepareCollectionAsync = prepareCollectionAsync;
        }

        // Methods.
        /// <summary>
        /// Create on a lock collection the TTL index collecting its abandoned lock documents:
        /// the documents whose owners died without releasing them, left expired with nobody
        /// taking them over. The server deletes them <see cref="AbandonedDocumentRetention"/>
        /// after their expiration, keeping the collection bounded without any cleanup task;
        /// a renewed lease keeps its expiration in the future, out of the collection reach.
        /// </summary>
        /// <param name="lockCollection">The collection persisting the lease documents</param>
        public static Task CreateAbandonedDocumentsTtlIndexAsync(IMongoCollection<BsonDocument> lockCollection)
        {
            ArgumentNullException.ThrowIfNull(lockCollection);

            return lockCollection.Indexes.CreateOneAsync(new CreateIndexModel<BsonDocument>(
                Builders<BsonDocument>.IndexKeys.Ascending(ExpirationTimeElementName),
                new CreateIndexOptions
                {
                    ExpireAfter = AbandonedDocumentRetention,
                    Name = AbandonedDocumentsTtlIndexName
                }));
        }

        public async Task<bool> IsLockedAsync() =>
            await lockCollection.CountDocumentsAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.Gt(ExpirationTimeElementName, DateTime.UtcNow))).ConfigureAwait(false) > 0;

        public Task<IResourceLockLease?> TryAcquireAsync(
            ResourceLockMode mode = ResourceLockMode.Exclusive,
            TimeSpan? leaseDuration = null) =>
            mode switch
            {
                ResourceLockMode.Exclusive => TryAcquireExclusiveAsync(leaseDuration),
                ResourceLockMode.Shared => TryAcquireSharedAsync(leaseDuration),
                _ => throw new ArgumentOutOfRangeException(nameof(mode))
            };

        public async Task<bool> TryClaimAsync(string ownerId, TimeSpan? leaseDuration = null)
        {
            ArgumentNullException.ThrowIfNull(ownerId);

            var claimedLeaseDuration = ResolveLeaseDuration(leaseDuration);
            await PrepareCollectionAsync().ConfigureAwait(false);

            //the claim is not a lease yet: the lease id stamps at resume
            return await TryClaimExclusiveAsync(ownerId, claimedLeaseDuration, leaseId: null).ConfigureAwait(false);
        }

        public IResourceLockLease? TryGetAmbientLease()
        {
            var leases = executionContext.TryGetItemsList<ResourceLockLease>(LeaseKey);
            if (leases is null)
                return null;

            /* Get the innermost lease of this same lock with a stack system, like the other
             * ambient handlers resolve their own: a flow can hold the leases of different
             * locks, and a lease of another lock doesn't own this one. */
            lock (((ICollection)leases).SyncRoot)
                return leases
                    .Where(lease => lease.LockId == lockId)
                    .Reverse()
                    .FirstOrDefault();
        }

        public Task TryReleaseAsync(string ownerId)
        {
            ArgumentNullException.ThrowIfNull(ownerId);

            return ReleaseExclusiveLockAsync(Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId));
        }

        public async Task<IResourceLockLease?> TryResumeClaimAsync(string ownerId)
        {
            ArgumentNullException.ThrowIfNull(ownerId);

            var leaseId = Guid.NewGuid().ToString();
            var leaseDuration = await TryStampLeaseAsync(ownerId, leaseId).ConfigureAwait(false);
            if (leaseDuration is null)
                return null;

            return await CreateLeaseReleasingOnFailureAsync(
                ownerId, leaseId, leaseDuration.Value, ResourceLockMode.Exclusive).ConfigureAwait(false);
        }

        // Helpers.
        private async Task<IResourceLockLease> CreateLeaseReleasingOnFailureAsync(
            string ownerId,
            string leaseId,
            TimeSpan leaseDuration,
            ResourceLockMode mode)
        {
            try
            {
                return new ResourceLockLease(this, ownerId, leaseId, leaseDuration, mode);
            }
            catch
            {
                //the claim already holds the lock: without an owning lease nobody would release it
                await ReleaseLeaseAsync(ownerId, leaseId, mode).ConfigureAwait(false);
                throw;
            }
        }

        private async Task<bool> HasLiveExclusiveLeaseAsync() =>
            await lockCollection.CountDocumentsAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.Exists(OwnerElementName),
                    Builders<BsonDocument>.Filter.Gt(ExpirationTimeElementName, DateTime.UtcNow))).ConfigureAwait(false) > 0;

        private static FilterDefinition<BsonDocument> OwnedLeaseFilter(string ownerId, string leaseId) =>
            Builders<BsonDocument>.Filter.And(
                Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId),
                Builders<BsonDocument>.Filter.Eq(LeaseIdElementName, leaseId));

        private Task PrepareCollectionAsync() =>
            prepareCollectionAsync?.Invoke() ?? Task.CompletedTask;

        private Task<DeleteResult> ReleaseExclusiveLockAsync(FilterDefinition<BsonDocument> ownershipFilter) =>
            lockCollection.DeleteOneAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    ownershipFilter));

        private Task ReleaseLeaseAsync(string ownerId, string leaseId, ResourceLockMode mode) =>
            mode is ResourceLockMode.Shared ?
                ReleaseSharedLeaseAsync(leaseId) :
                ReleaseExclusiveLockAsync(OwnedLeaseFilter(ownerId, leaseId));

        private async Task ReleaseSharedLeaseAsync(string leaseId)
        {
            /* The release filter requires the own lease entry: a document not carrying it
             * anymore (taken over after a full expiration, or collected) stays untouched. */
            var releasedDocument = await lockCollection.FindOneAndUpdateAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.ElemMatch(SharedLeasesElementName,
                        Builders<BsonDocument>.Filter.Eq(LeaseIdElementName, leaseId))),
                Builders<BsonDocument>.Update.Pipeline(PipelineDefinition<BsonDocument, BsonDocument>.Create(
                    //drop the released lease, and the expired entries of dead holders with it
                    new BsonDocument("$set", new BsonDocument(SharedLeasesElementName,
                        new BsonDocument("$filter", new BsonDocument
                        {
                            ["input"] = "$" + SharedLeasesElementName,
                            ["as"] = "lease",
                            ["cond"] = new BsonDocument("$and", new BsonArray
                            {
                                new BsonDocument("$ne", new BsonArray { "$$lease." + LeaseIdElementName, leaseId }),
                                new BsonDocument("$gt", new BsonArray { "$$lease." + ExpirationTimeElementName, "$$NOW" })
                            })
                        }))),
                    /* Recompute the expiration on the remaining leases: the released holder
                     * could have been the furthest one, and a lock emptied by its last holder
                     * must open to exclusive claims right away, not at the stale expiration. */
                    new BsonDocument("$set", new BsonDocument(ExpirationTimeElementName,
                        new BsonDocument("$cond", new BsonArray
                        {
                            new BsonDocument("$gt", new BsonArray { new BsonDocument("$size", "$" + SharedLeasesElementName), 0 }),
                            new BsonDocument("$max", "$" + SharedLeasesElementName + "." + ExpirationTimeElementName),
                            "$$NOW"
                        }))))),
                new FindOneAndUpdateOptions<BsonDocument, BsonDocument>
                {
                    ReturnDocument = ReturnDocument.After
                }).ConfigureAwait(false);

            // Delete the emptied lock document, without waiting its garbage collection.
            /* The delete is guarded: a shared acquisition landing in between appended its own
             * lease, and an exclusive claim its ownership, so the document survives them. */
            if (releasedDocument is not null &&
                releasedDocument.GetValue(SharedLeasesElementName, new BsonArray()).AsBsonArray.Count == 0)
                await lockCollection.DeleteOneAsync(
                    Builders<BsonDocument>.Filter.And(
                        Builders<BsonDocument>.Filter.Eq("_id", lockId),
                        Builders<BsonDocument>.Filter.Size(SharedLeasesElementName, 0),
                        Builders<BsonDocument>.Filter.Exists(OwnerElementName, false))).ConfigureAwait(false);
        }

        private static TimeSpan ResolveLeaseDuration(TimeSpan? leaseDuration)
        {
            var resolvedLeaseDuration = leaseDuration ?? DefaultLeaseDuration;
            ArgumentOutOfRangeException.ThrowIfLessThan(resolvedLeaseDuration, MinLeaseDuration, nameof(leaseDuration));
            return resolvedLeaseDuration;
        }

        private async Task<IResourceLockLease?> TryAcquireExclusiveAsync(TimeSpan? leaseDuration)
        {
            var acquiredLeaseDuration = ResolveLeaseDuration(leaseDuration);
            await PrepareCollectionAsync().ConfigureAwait(false);

            /* The acquirer is claimer and renewer at once: the lease id stamps with the claim
             * itself, so the acquisition is a single round trip, without the resume step. */
            var ownerId = Guid.NewGuid().ToString();
            var leaseId = Guid.NewGuid().ToString();
            if (!await TryClaimExclusiveAsync(ownerId, acquiredLeaseDuration, leaseId).ConfigureAwait(false))
                return null;

            return await CreateLeaseReleasingOnFailureAsync(
                ownerId, leaseId, acquiredLeaseDuration, ResourceLockMode.Exclusive).ConfigureAwait(false);
        }

        private async Task<IResourceLockLease?> TryAcquireSharedAsync(TimeSpan? leaseDuration)
        {
            var acquiredLeaseDuration = ResolveLeaseDuration(leaseDuration);
            await PrepareCollectionAsync().ConfigureAwait(false);

            var ownerId = Guid.NewGuid().ToString();
            var leaseId = Guid.NewGuid().ToString();
            for (var attempt = 1; ; attempt++)
            {
                if (await TryClaimSharedAsync(ownerId, leaseId, acquiredLeaseDuration).ConfigureAwait(false))
                    break;

                /* The upsert insert collided on the id index: a live exclusive lease, or a
                 * concurrent shared acquisition inserting the first lease of the resource.
                 * One read tells them apart: only the exclusive lease is a denial, while a
                 * concurrent shared holder admits this one, whose next attempt appends to
                 * the document existing now. */
                if (attempt >= SharedAcquireMaxAttempts ||
                    await HasLiveExclusiveLeaseAsync().ConfigureAwait(false))
                    return null;
            }

            return await CreateLeaseReleasingOnFailureAsync(
                ownerId, leaseId, acquiredLeaseDuration, ResourceLockMode.Shared).ConfigureAwait(false);
        }

        private async Task<bool> TryClaimExclusiveAsync(string ownerId, TimeSpan leaseDuration, string? leaseId)
        {
            var now = DateTime.UtcNow;
            var claimUpdate = Builders<BsonDocument>.Update
                .Set(OwnerElementName, ownerId)
                .Set(ExpirationTimeElementName, now + leaseDuration)
                .Set(LeaseDurationTicksElementName, leaseDuration.Ticks)
                //a taken over shared document drops the expired leases it still carries
                .Unset(SharedLeasesElementName);
            claimUpdate = leaseId is null
                ? claimUpdate.Unset(LeaseIdElementName)
                : claimUpdate.Set(LeaseIdElementName, leaseId);

            try
            {
                /* The expiration comparison is type bracketed on the server: a document
                 * without a date expiration matches no comparison, so it takes an explicit
                 * type predicate to be claimable instead of deadlocking the lock forever. */
                await lockCollection.UpdateOneAsync(
                    Builders<BsonDocument>.Filter.And(
                        Builders<BsonDocument>.Filter.Eq("_id", lockId),
                        Builders<BsonDocument>.Filter.Or(
                            Builders<BsonDocument>.Filter.Lt(ExpirationTimeElementName, now),
                            Builders<BsonDocument>.Filter.Not(
                                Builders<BsonDocument>.Filter.Type(ExpirationTimeElementName, BsonType.DateTime)))),
                    claimUpdate,
                    new UpdateOptions { IsUpsert = true }).ConfigureAwait(false);

                return true;
            }
            catch (MongoWriteException e) when (e.WriteError is { Category: ServerErrorCategory.DuplicateKey })
            {
                //another owner holds a live lease
                return false;
            }
        }

        private async Task<bool> TryClaimSharedAsync(string ownerId, string leaseId, TimeSpan leaseDuration)
        {
            var now = DateTime.UtcNow;
            var newLeaseEntry = new BsonDocument
            {
                [ExpirationTimeElementName] = now + leaseDuration,
                [LeaseIdElementName] = leaseId,
                [OwnerElementName] = ownerId
            };

            try
            {
                //only a live exclusive lease denies: any shared document, and any expired one, admits
                await lockCollection.UpdateOneAsync(
                    Builders<BsonDocument>.Filter.And(
                        Builders<BsonDocument>.Filter.Eq("_id", lockId),
                        Builders<BsonDocument>.Filter.Or(
                            Builders<BsonDocument>.Filter.Exists(OwnerElementName, false),
                            Builders<BsonDocument>.Filter.Lt(ExpirationTimeElementName, now),
                            Builders<BsonDocument>.Filter.Not(
                                Builders<BsonDocument>.Filter.Type(ExpirationTimeElementName, BsonType.DateTime)))),
                    Builders<BsonDocument>.Update.Pipeline(PipelineDefinition<BsonDocument, BsonDocument>.Create(
                        //append the own lease, dropping the expired entries with the same write
                        new BsonDocument("$set", new BsonDocument(SharedLeasesElementName,
                            new BsonDocument("$concatArrays", new BsonArray
                            {
                                new BsonDocument("$filter", new BsonDocument
                                {
                                    ["input"] = new BsonDocument("$ifNull", new BsonArray { "$" + SharedLeasesElementName, new BsonArray() }),
                                    ["as"] = "lease",
                                    ["cond"] = new BsonDocument("$gt", new BsonArray { "$$lease." + ExpirationTimeElementName, now })
                                }),
                                new BsonArray { newLeaseEntry }
                            }))),
                        //the top level expiration tracks the furthest lease: claims, state reads and TTL read it
                        new BsonDocument("$set", new BsonDocument(ExpirationTimeElementName,
                            new BsonDocument("$max", "$" + SharedLeasesElementName + "." + ExpirationTimeElementName))),
                        //a taken over exclusive lease clears its ownership elements
                        new BsonDocument("$unset", new BsonArray { OwnerElementName, LeaseIdElementName, LeaseDurationTicksElementName }))),
                    new UpdateOptions { IsUpsert = true }).ConfigureAwait(false);

                return true;
            }
            catch (MongoWriteException e) when (e.WriteError is { Category: ServerErrorCategory.DuplicateKey })
            {
                //a live exclusive lease, or a concurrent acquisition inserting the document
                return false;
            }
        }

        private async Task<bool> TryRenewExclusiveLeaseAsync(string ownerId, string leaseId, TimeSpan leaseDuration)
        {
            var result = await lockCollection.UpdateOneAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    OwnedLeaseFilter(ownerId, leaseId)),
                Builders<BsonDocument>.Update
                    .Set(ExpirationTimeElementName, DateTime.UtcNow + leaseDuration)).ConfigureAwait(false);

            return result.MatchedCount > 0;
        }

        private async Task<bool> TryRenewSharedLeaseAsync(string leaseId, TimeSpan leaseDuration)
        {
            var newExpirationTime = DateTime.UtcNow + leaseDuration;
            var result = await lockCollection.UpdateOneAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.ElemMatch(SharedLeasesElementName,
                        Builders<BsonDocument>.Filter.Eq(LeaseIdElementName, leaseId))),
                Builders<BsonDocument>.Update
                    .Set(SharedLeasesElementName + ".$." + ExpirationTimeElementName, newExpirationTime)
                    //the top level expiration keeps tracking the furthest lease
                    .Max(ExpirationTimeElementName, newExpirationTime)).ConfigureAwait(false);

            return result.MatchedCount > 0;
        }

        /// <summary>
        /// Stamp a fresh lease id on the lock document of an owner, reading back the lease
        /// duration its claim chose, and extend the expiration by it.
        /// </summary>
        /// <param name="ownerId">The owner identifier used by the claim</param>
        /// <param name="leaseId">The lease identifier of this resume</param>
        /// <returns>The lease duration the renewals must use, or null when the owner doesn't
        /// hold the lock anymore</returns>
        private async Task<TimeSpan?> TryStampLeaseAsync(string ownerId, string leaseId)
        {
            var leaseDocument = await lockCollection.FindOneAndUpdateAsync(
                Builders<BsonDocument>.Filter.And(
                    Builders<BsonDocument>.Filter.Eq("_id", lockId),
                    Builders<BsonDocument>.Filter.Eq(OwnerElementName, ownerId)),
                Builders<BsonDocument>.Update
                    .Set(LeaseIdElementName, leaseId),
                new FindOneAndUpdateOptions<BsonDocument, BsonDocument>
                {
                    ReturnDocument = ReturnDocument.After
                }).ConfigureAwait(false);

            if (leaseDocument is null)
                return null;

            /* A lease document carrying no duration, or one too short to derive a renewal
             * interval from, renews on the default: the alternative would be a claim nobody
             * can resume, holding the lock until its expiration. */
            var leaseDuration =
                leaseDocument.TryGetValue(LeaseDurationTicksElementName, out var leaseDurationTicks) &&
                leaseDurationTicks.IsNumeric &&
                leaseDurationTicks.ToInt64() >= MinLeaseDuration.Ticks
                    ? TimeSpan.FromTicks(leaseDurationTicks.ToInt64())
                    : DefaultLeaseDuration;

            //the stamp doesn't extend the expiration by itself: the first renewal of the lease does
            return await TryRenewExclusiveLeaseAsync(ownerId, leaseId, leaseDuration).ConfigureAwait(false)
                ? leaseDuration
                : null;
        }

        // Nested types.
        private sealed class ResourceLockLease : IResourceLockLease
        {
            // Fields.
            private readonly IAsyncLocalContextHandler? asyncLocalContextHandler;
            private int disposals;
            private DateTime lastRenewalTime;
            private readonly TimeSpan leaseDuration;
            private readonly string leaseId;
            private readonly CancellationTokenSource leaseLostTokenSource = new();
            private readonly ICollection<ResourceLockLease> leases;
            private readonly ResourceLockMode mode;
            private readonly TimeSpan renewalInterval;
            private readonly CancellationTokenSource renewalStopTokenSource = new();
            private readonly Task renewalTask;
            private readonly ResourceLock resourceLock;

            // Constructor and dispose.
            public ResourceLockLease(
                ResourceLock resourceLock,
                string ownerId,
                string leaseId,
                TimeSpan leaseDuration,
                ResourceLockMode mode)
            {
                this.leaseDuration = leaseDuration;
                this.leaseId = leaseId;
                this.mode = mode;
                this.resourceLock = resourceLock;
                //the duration chosen by the claim drives the renewals of whoever holds its lease
                renewalInterval = leaseDuration / RenewalsPerLease;
                OwnerId = ownerId;
                lastRenewalTime = DateTime.UtcNow; //the claim or resume already renewed the lease

                var executionContext = resourceLock.executionContext;

                if (executionContext.Items is null) //if an execution context doesn't exist, create it
                    asyncLocalContextHandler = AsyncLocalContext.Instance.InitAsyncLocalContext();

                leases = executionContext.GetOrAddItemsList<ResourceLockLease>(LeaseKey);

                lock (((ICollection)leases).SyncRoot)
                    leases.Add(this);

                renewalTask = KeepLeaseRenewedAsync();
            }

            public async ValueTask DisposeAsync()
            {
                if (Interlocked.Exchange(ref disposals, 1) != 0)
                    return;

                // Stop the background renewal.
                /* A faulted renewal task must neither skip the release below, nor replace the
                 * exception of the work run under the lease: report it and proceed. */
                try
                {
                    await renewalStopTokenSource.CancelAsync().ConfigureAwait(false);
                    await renewalTask.ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    resourceLock.logger.ResourceLockLeaseRenewalFailed(resourceLock.lockId, OwnerId, e);
                }

                lock (((ICollection)leases).SyncRoot)
                    leases.Remove(this);

                // Release the lock, permitting new claims without waiting the lease expiration.
                /* The release is guarded by the lease id: releasing a lease already taken
                 * over, or invalidated by another resume of the same owner, is a no-op. A
                 * release failing (e.g. an unreachable server) leaves the lease expiring on
                 * its own: log it, without masking any exception of the work run under it. */
                try
                {
                    await ReleaseAsync().ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    resourceLock.logger.ResourceLockReleaseFailed(resourceLock.lockId, OwnerId, e);
                }

                leaseLostTokenSource.Dispose();
                renewalStopTokenSource.Dispose();
                asyncLocalContextHandler?.Dispose();
            }

            // Properties.
            public CancellationToken LeaseLostToken => leaseLostTokenSource.Token;
            //identifies the lock owning this lease, resolving the ambient leases of a flow
            public string LockId => resourceLock.lockId;
            public string OwnerId { get; }

            // Helpers.
            private async Task KeepLeaseRenewedAsync()
            {
                try
                {
                    while (true)
                    {
                        await Task.Delay(renewalInterval, renewalStopTokenSource.Token).ConfigureAwait(false);
                        try
                        {
                            if (await TryRenewAsync().ConfigureAwait(false))
                            {
                                lastRenewalTime = DateTime.UtcNow;
                                continue;
                            }

                            //the lease has been taken over, or invalidated by another resume
                            resourceLock.logger.ResourceLockLeaseLost(resourceLock.lockId, OwnerId);
                        }
                        catch (Exception e) when (e is not OperationCanceledException)
                        {
                            /* A transient failure: keep renewing, the lease survives until its
                             * expiration. Renewals failing for the whole lease duration end it:
                             * the lease can't be assumed alive anymore, and another claimer can
                             * already have taken the lock over. */
                            resourceLock.logger.ResourceLockLeaseRenewalFailed(resourceLock.lockId, OwnerId, e);

                            if (DateTime.UtcNow - lastRenewalTime < leaseDuration)
                                continue;

                            resourceLock.logger.ResourceLockLeaseLost(resourceLock.lockId, OwnerId);
                        }

                        await leaseLostTokenSource.CancelAsync().ConfigureAwait(false);
                        return;
                    }
                }
                catch (OperationCanceledException)
                {
                    //normal renewal stop at disposal
                }
            }

            private Task ReleaseAsync() => resourceLock.ReleaseLeaseAsync(OwnerId, leaseId, mode);

            private Task<bool> TryRenewAsync() => mode is ResourceLockMode.Shared
                ? resourceLock.TryRenewSharedLeaseAsync(leaseId, leaseDuration)
                : resourceLock.TryRenewExclusiveLeaseAsync(OwnerId, leaseId, leaseDuration);
        }
    }
}
