// Copyright 2020-present Etherna SA
// This file is part of Scrinium.
//
// Scrinium is free software: you can redistribute it and/or modify it under the terms of the
// GNU Lesser General Public License as published by the Free Software Foundation,
// either version 3 of the License, or (at your option) any later version.
//
// Scrinium is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along with Scrinium.
// If not, see <https://www.gnu.org/licenses/>.

using Etherna.MongoDB.Bson;
using Etherna.MongoDB.Driver;
using Etherna.Scrinium.Core.Domain.Models;
using Etherna.Scrinium.Core.Extensions;
using Etherna.Scrinium.Core.Options;
using Etherna.Scrinium.Core.Repositories;
using Etherna.Scrinium.Core.Serialization.Mapping;
using Etherna.Scrinium.Core.Utility;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;

namespace Etherna.Scrinium.Core.Tasks
{
    public class DeleteDocDependenciesTask(
        ILogger<DeleteDocDependenciesTask> logger,
        IServiceProvider serviceProvider)
        : IDeleteDocDependenciesTask
    {
        // Consts.
        /* Cascade deletes load the referencing models to delete them with a domain delete,
         * one batch at a time inside a transient models scope: the batch bounds the loaded
         * models memory and the scope evicts them, whatever the cascade fan out. */
        private const int CascadeDeleteBatchSize = 100;

        // Methods.
        public async Task RunAsync<TDbContext>(
            Type deletedDbContextType,
            string deletedRepositoryName,
            object deletedModelId,
            IEnumerable<string> idMemberMapIdentifiers)
            where TDbContext : class, IDbContext
        {
            ArgumentNullException.ThrowIfNull(deletedDbContextType);
            ArgumentNullException.ThrowIfNull(deletedModelId);
            ArgumentNullException.ThrowIfNull(idMemberMapIdentifiers);

            logger.DeleteDocDependenciesTaskStarted(typeof(TDbContext), deletedRepositoryName, deletedModelId.ToString()!, idMemberMapIdentifiers);

            // Get dbcontext.
            var dbContext = (TDbContext)serviceProvider.GetService(typeof(TDbContext))!;
            using var dbExecutionContext = new DbExecutionContextHandler(dbContext); //run into a db execution context

            /* The task never holds an exclusive access allowance: executed during an
             * exclusive access (e.g. a migration), its collection accesses throw, and the
             * task executor retries later — background propagation stays out of exclusive
             * works, and converges on their outcome. */

            // Recover the reference id member maps.
            /*
             * Verify that each member map still exists, still declares an origin delete policy,
             * and still resolves its source on the repository the model was deleted from —
             * verified against the db context type and repository name carried by the payload,
             * since repository names are unique per db context only: a scheduled task could
             * execute with a configuration different from the one that enqueued it, for
             * example after a software upgrade.
             */
            var idMemberMaps = idMemberMapIdentifiers
                .Select(idMemberMapIdentifier => dbContext.Engine.MapRegistry.MemberMapsById.TryGetValue(idMemberMapIdentifier, out var idmm) ? idmm : null!)
                .Where(idMemberMap => idMemberMap is not null &&
                    idMemberMap.TryFindHostingReferenceSerializer() is { } referenceSerializer &&
                    referenceSerializer.Configuration.OriginDelete != OriginDeleteMode.KeepReference &&
                    referenceSerializer.TryResolveSourceRepository(dbContext) is { } sourceRepository &&
                    sourceRepository.Name == deletedRepositoryName &&
                    sourceRepository.DbContext.Engine.DbContextType == deletedDbContextType);

            // Propagate on each repository hosting the referencing documents.
            /*
             * Like the dependencies update task, the id member maps fan out to every repository
             * whose model type can host the path root documents. The member maps generated by
             * different schemas on the same element path group together: the removal shape
             * follows the active schemas, and the applied policy is the most invasive one of
             * the group, mirroring how an instance reached by more references keeps the
             * strictest missing origin document mode.
             */
            foreach (var repository in dbContext.RepositoryRegistry.Repositories)
            {
                /* A read-only repository consumes documents owned by another application:
                 * they are not this task's to repair, and every write would be denied. */
                if (repository.IsReadOnly)
                    continue;

                var propagateAsyncMethodInfo = typeof(DeleteDocDependenciesTask)
                    .GetMethod(nameof(PropagateAsync), BindingFlags.NonPublic | BindingFlags.Static)!
                    .MakeGenericMethod(repository.ModelType, repository.KeyType);

                var pathGroups = idMemberMaps
                    .Where(idMemberMap => repository.ModelType.IsAssignableFrom(
                        idMemberMap.MemberMapPath.First().ModelMapSchema.ModelMap.ModelType))
                    .GroupBy(idMemberMap => idMemberMap.RenderElementPath(false, _ => ".$", _ => ".*"), StringComparer.Ordinal);

                foreach (var pathGroup in pathGroups)
                {
                    var representativeIdMemberMap = pathGroup
                        .OrderByDescending(idMemberMap => idMemberMap.IsGeneratedByActiveSchemas)
                        .First();

                    /* A path with an unknown document key, or a fixed array position, can't be
                     * addressed with a filter: its references stay, found by the missing origin
                     * references scan. */
                    var removalShape = ReferenceRemovalShape.TryCreate(representativeIdMemberMap);
                    if (removalShape is null)
                        continue;

                    var originDeleteMode = pathGroup
                        .Select(idMemberMap => idMemberMap.TryFindHostingReferenceSerializer()!.Configuration.OriginDelete)
                        .Max();

                    // Serialize the deleted id like the references store it.
                    var deletedIdValue = representativeIdMemberMap.Serializer.SerializeToBsonValue(deletedModelId);

                    await ((Task)propagateAsyncMethodInfo.Invoke(null,
                    [
                        repository,
                        dbContext,
                        removalShape,
                        deletedIdValue,
                        originDeleteMode
                    ])!).ConfigureAwait(false);
                }
            }

            logger.DeleteDocDependenciesTaskEnded(typeof(TDbContext), deletedRepositoryName, deletedModelId.ToString()!);
        }

        // Helpers.
        private static async Task PropagateAsync<TOriginModel, TOriginKey>(
            IRepository<TOriginModel, TOriginKey> repository,
            IDbContext dbContext,
            ReferenceRemovalShape removalShape,
            BsonValue deletedIdValue,
            OriginDeleteMode originDeleteMode)
            where TOriginModel : class, IEntityModel<TOriginKey>
        {
            if (originDeleteMode == OriginDeleteMode.DeleteReferencingDocument)
            {
                // Delete the referencing documents with a domain delete, batch by batch.
                /* The domain delete propagates the deleted documents' own reference policies
                 * in turn, chaining the cascade; the loop always reads the documents still
                 * referencing the deleted id, so what a batch deleted doesn't match anymore,
                 * and mutual references terminate on the documents already deleted. */
                while (true)
                {
                    using var transientScope = dbContext.StartTransientModelsScope();

                    List<TOriginModel> referencingModels;
                    using (var referencingModelsCursor = await repository.FindAsync(
                        removalShape.BuildFilter(deletedIdValue),
                        new FindOptions<TOriginModel, TOriginModel> { Limit = CascadeDeleteBatchSize }).ConfigureAwait(false))
                    {
                        referencingModels = await referencingModelsCursor.ToListAsync().ConfigureAwait(false);
                    }
                    if (referencingModels.Count == 0)
                        return;

                    foreach (var referencingModel in referencingModels)
                        await repository.DeleteAsync(referencingModel).ConfigureAwait(false);
                }
            }

            // Remove the references from the referencing documents, with one update.
            /* The update addresses the documents still carrying the deleted id at the path: a
             * reference concurrently rewritten to another document doesn't match anymore, and
             * stays untouched. */
            var (update, arrayFilter) = removalShape.BuildUpdate(deletedIdValue);
            await repository.UpdateManyAsync(
                removalShape.BuildFilter(deletedIdValue),
                update,
                arrayFilter is null ? null : new UpdateOptions
                {
                    ArrayFilters = [new BsonDocumentArrayFilterDefinition<BsonDocument>(arrayFilter)]
                }).ConfigureAwait(false);
        }
    }
}
