name: Stable release deploy to NuGet

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:8
        ports:
          - 27017:27017

    env:
      MONGODM_TEST_DB_URL: mongodb://localhost:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release

      - name: Generate nuget package
        run: dotnet pack --configuration Release -o nupkg

      - name: Push packages
        run: dotnet nuget push './nupkg/*.nupkg' --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json
